//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buttercup.Control.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Buttercup.Control.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Online Digital Talking Book Reader (Demo).
        /// </summary>
        public static string Application_CatchPhrase {
            get {
                return ResourceManager.GetString("Application_CatchPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttercup Reader.
        /// </summary>
        public static string Application_Title {
            get {
                return ResourceManager.GetString("Application_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website: http://www.buttercupreader.net.
        /// </summary>
        public static string Application_WebSite {
            get {
                return ResourceManager.GetString("Application_WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark your current position in the book.
        /// </summary>
        public static string AutomationHelp_AddBookmark {
            get {
                return ResourceManager.GetString("AutomationHelp_AddBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Information Button.
        /// </summary>
        public static string AutomationHelp_BookInfo {
            get {
                return ResourceManager.GetString("AutomationHelp_BookInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the buttercup contrast scheme using the Up and Down arrow keys..
        /// </summary>
        public static string AutomationHelp_ChangeContrast {
            get {
                return ResourceManager.GetString("AutomationHelp_ChangeContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the size of the interface by clicking the button and using the slider, or directly via the keyboard shortcuts Shift+J and Shift+K..
        /// </summary>
        public static string AutomationHelp_ChangeSize {
            get {
                return ResourceManager.GetString("AutomationHelp_ChangeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Display Settings Panel. Use this panel to change the scale and contrast scheme of the Buttercup reader..
        /// </summary>
        public static string AutomationHelp_DisplaySettings {
            get {
                return ResourceManager.GetString("AutomationHelp_DisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Find Panel. Use this panel to go to a particular page or find specific text within the currently opened book..
        /// </summary>
        public static string AutomationHelp_Find {
            get {
                return ResourceManager.GetString("AutomationHelp_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;Enter&apos; to begin search.
        /// </summary>
        public static string AutomationHelp_Find_Activate {
            get {
                return ResourceManager.GetString("AutomationHelp_Find_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the text you would like to find in the book.
        /// </summary>
        public static string AutomationHelp_Find_Input {
            get {
                return ResourceManager.GetString("AutomationHelp_Find_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the page number you would like to go to.
        /// </summary>
        public static string AutomationHelp_GoToPage {
            get {
                return ResourceManager.GetString("AutomationHelp_GoToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;Enter&apos; to go to page.
        /// </summary>
        public static string AutomationHelp_GoToPage_Activate {
            get {
                return ResourceManager.GetString("AutomationHelp_GoToPage_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Help panel. Here, you can get help on how to use the Buttercup reader..
        /// </summary>
        public static string AutomationHelp_Help {
            get {
                return ResourceManager.GetString("AutomationHelp_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide the currently open panel.
        /// </summary>
        public static string AutomationHelp_HidePanel {
            get {
                return ResourceManager.GetString("AutomationHelp_HidePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Storage Button.
        /// </summary>
        public static string AutomationHelp_IncreaseIS {
            get {
                return ResourceManager.GetString("AutomationHelp_IncreaseIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Navigation Panel. View Book Information, Table of Contents and Bookmarks..
        /// </summary>
        public static string AutomationHelp_Navigation {
            get {
                return ResourceManager.GetString("AutomationHelp_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate through the Table of Contents using the Up and Down Arrow Keys..
        /// </summary>
        public static string AutomationHelp_Navigation_Content {
            get {
                return ResourceManager.GetString("AutomationHelp_Navigation_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between Book Information, Table of Contents and Bookmark views, use the Up and Down Arrow Keys to switch between them..
        /// </summary>
        public static string AutomationHelp_NavigationPanel {
            get {
                return ResourceManager.GetString("AutomationHelp_NavigationPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the Next Heading.
        /// </summary>
        public static string AutomationHelp_NextSection {
            get {
                return ResourceManager.GetString("AutomationHelp_NextSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the Next Paragraph.
        /// </summary>
        public static string AutomationHelp_NextSentence {
            get {
                return ResourceManager.GetString("AutomationHelp_NextSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Daisy book from your local computer.
        /// </summary>
        public static string AutomationHelp_OpenBook {
            get {
                return ResourceManager.GetString("AutomationHelp_OpenBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause playback of the current book.
        /// </summary>
        public static string AutomationHelp_Pause {
            get {
                return ResourceManager.GetString("AutomationHelp_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start playback of the current book.
        /// </summary>
        public static string AutomationHelp_Play {
            get {
                return ResourceManager.GetString("AutomationHelp_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the Previous Heading.
        /// </summary>
        public static string AutomationHelp_PreviousSection {
            get {
                return ResourceManager.GetString("AutomationHelp_PreviousSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the Previous Paragraph.
        /// </summary>
        public static string AutomationHelp_PreviousSentence {
            get {
                return ResourceManager.GetString("AutomationHelp_PreviousSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide to Adjust Volume.
        /// </summary>
        public static string AutomationHelp_VolumeSlider {
            get {
                return ResourceManager.GetString("AutomationHelp_VolumeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bookmark.
        /// </summary>
        public static string AutomationName_AddBookmark {
            get {
                return ResourceManager.GetString("AutomationName_AddBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Book Info.
        /// </summary>
        public static string AutomationName_BookInfo {
            get {
                return ResourceManager.GetString("AutomationName_BookInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Search TextBox.
        /// </summary>
        public static string AutomationName_ClearText {
            get {
                return ResourceManager.GetString("AutomationName_ClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Panel.
        /// </summary>
        public static string AutomationName_ClosePanel {
            get {
                return ResourceManager.GetString("AutomationName_ClosePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        public static string AutomationName_Contrast {
            get {
                return ResourceManager.GetString("AutomationName_Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast: Black Text on White Background.
        /// </summary>
        public static string AutomationName_Contrast_BlackWhite {
            get {
                return ResourceManager.GetString("AutomationName_Contrast_BlackWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast: White Text on Blue Background.
        /// </summary>
        public static string AutomationName_Contrast_WhiteBlue {
            get {
                return ResourceManager.GetString("AutomationName_Contrast_WhiteBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast: Yellow Text on Black Background.
        /// </summary>
        public static string AutomationName_Contrast_YellowBlack {
            get {
                return ResourceManager.GetString("AutomationName_Contrast_YellowBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Volume.
        /// </summary>
        public static string AutomationName_DecreaseVolume {
            get {
                return ResourceManager.GetString("AutomationName_DecreaseVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Settings.
        /// </summary>
        public static string AutomationName_DisplaySettings {
            get {
                return ResourceManager.GetString("AutomationName_DisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Text.
        /// </summary>
        public static string AutomationName_Find {
            get {
                return ResourceManager.GetString("AutomationName_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to First Heading.
        /// </summary>
        public static string AutomationName_FirstSection {
            get {
                return ResourceManager.GetString("AutomationName_FirstSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Page.
        /// </summary>
        public static string AutomationName_GoToPage {
            get {
                return ResourceManager.GetString("AutomationName_GoToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Help.
        /// </summary>
        public static string AutomationName_Help {
            get {
                return ResourceManager.GetString("AutomationName_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Panel.
        /// </summary>
        public static string AutomationName_HidePanel {
            get {
                return ResourceManager.GetString("AutomationName_HidePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Storage.
        /// </summary>
        public static string AutomationName_IncreaseIS {
            get {
                return ResourceManager.GetString("AutomationName_IncreaseIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Volume.
        /// </summary>
        public static string AutomationName_IncreaseVolume {
            get {
                return ResourceManager.GetString("AutomationName_IncreaseVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Last Heading.
        /// </summary>
        public static string AutomationName_LastSection {
            get {
                return ResourceManager.GetString("AutomationName_LastSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Navigation.
        /// </summary>
        public static string AutomationName_Navigation {
            get {
                return ResourceManager.GetString("AutomationName_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Information.
        /// </summary>
        public static string AutomationName_Navigation_BookInformation {
            get {
                return ResourceManager.GetString("AutomationName_Navigation_BookInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string AutomationName_Navigation_Bookmark {
            get {
                return ResourceManager.GetString("AutomationName_Navigation_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of Contents.
        /// </summary>
        public static string AutomationName_Navigation_Content {
            get {
                return ResourceManager.GetString("AutomationName_Navigation_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Next Page.
        /// </summary>
        public static string AutomationName_NextPage {
            get {
                return ResourceManager.GetString("AutomationName_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Next Header.
        /// </summary>
        public static string AutomationName_NextSection {
            get {
                return ResourceManager.GetString("AutomationName_NextSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Next Phrase.
        /// </summary>
        public static string AutomationName_NextSentence {
            get {
                return ResourceManager.GetString("AutomationName_NextSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Book.
        /// </summary>
        public static string AutomationName_OpenBook {
            get {
                return ResourceManager.GetString("AutomationName_OpenBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Book.
        /// </summary>
        public static string AutomationName_Pause {
            get {
                return ResourceManager.GetString("AutomationName_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Book.
        /// </summary>
        public static string AutomationName_Play {
            get {
                return ResourceManager.GetString("AutomationName_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play or Pause.
        /// </summary>
        public static string AutomationName_PlayPause {
            get {
                return ResourceManager.GetString("AutomationName_PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Previous Page.
        /// </summary>
        public static string AutomationName_PreviousPage {
            get {
                return ResourceManager.GetString("AutomationName_PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Previous Header.
        /// </summary>
        public static string AutomationName_PreviousSection {
            get {
                return ResourceManager.GetString("AutomationName_PreviousSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Previous Phrase.
        /// </summary>
        public static string AutomationName_PreviousSentence {
            get {
                return ResourceManager.GetString("AutomationName_PreviousSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Action.
        /// </summary>
        public static string AutomationName_StartAction {
            get {
                return ResourceManager.GetString("AutomationName_StartAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Backward.
        /// </summary>
        public static string AutomationName_TabBackward {
            get {
                return ResourceManager.GetString("AutomationName_TabBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Forward.
        /// </summary>
        public static string AutomationName_TabForward {
            get {
                return ResourceManager.GetString("AutomationName_TabForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute or Un-Mute.
        /// </summary>
        public static string AutomationName_ToggleMute {
            get {
                return ResourceManager.GetString("AutomationName_ToggleMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string AutomationName_VolumeSlider {
            get {
                return ResourceManager.GetString("AutomationName_VolumeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string AutomationName_ZoomIn {
            get {
                return ResourceManager.GetString("AutomationName_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        public static string AutomationName_ZoomOut {
            get {
                return ResourceManager.GetString("AutomationName_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Size.
        /// </summary>
        public static string ChangeSize {
            get {
                return ResourceManager.GetString("ChangeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Text on White Background.
        /// </summary>
        public static string Contrast_BlackWhite {
            get {
                return ResourceManager.GetString("Contrast_BlackWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Text on Blue Background.
        /// </summary>
        public static string Contrast_WhiteBlue {
            get {
                return ResourceManager.GetString("Contrast_WhiteBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Text on Black Background.
        /// </summary>
        public static string Contrast_YellowBlack {
            get {
                return ResourceManager.GetString("Contrast_YellowBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files (*.zip)|*.zip.
        /// </summary>
        public static string FileOpenDialogFilter {
            get {
                return ResourceManager.GetString("FileOpenDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to defaultListItem.
        /// </summary>
        public static string ListItemStyleKey {
            get {
                return ResourceManager.GetString("ListItemStyleKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string Main_GetStarted {
            get {
                return ResourceManager.GetString("Main_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To open a DAISY DTB from your Hard Drive, press &apos;O&apos;..
        /// </summary>
        public static string Main_OpenFromHdd {
            get {
                return ResourceManager.GetString("Main_OpenFromHdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To open the ButtercupReader Help Guide, press &apos;Shift+?&apos;..
        /// </summary>
        public static string Main_OpenHelp {
            get {
                return ResourceManager.GetString("Main_OpenHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [No book loaded].
        /// </summary>
        public static string NoBook_TitleMessage {
            get {
                return ResourceManager.GetString("NoBook_TitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark your current position in the book.
        /// </summary>
        public static string ToolTip_AddBookmark {
            get {
                return ResourceManager.GetString("ToolTip_AddBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Book Information Panel.
        /// </summary>
        public static string ToolTip_BookInfo {
            get {
                return ResourceManager.GetString("ToolTip_BookInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide to adjust reading delay.
        /// </summary>
        public static string ToolTip_DelaySlider {
            get {
                return ResourceManager.GetString("ToolTip_DelaySlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Display Settings Panel (D).
        /// </summary>
        public static string ToolTip_DisplaySettings {
            get {
                return ResourceManager.GetString("ToolTip_DisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Find Panel (F).
        /// </summary>
        public static string ToolTip_Find {
            get {
                return ResourceManager.GetString("ToolTip_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search (F).
        /// </summary>
        public static string ToolTip_Find_Activate {
            get {
                return ResourceManager.GetString("ToolTip_Find_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Page (P).
        /// </summary>
        public static string ToolTip_GoToPage {
            get {
                return ResourceManager.GetString("ToolTip_GoToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Help panel (Shift+?).
        /// </summary>
        public static string ToolTip_Help {
            get {
                return ResourceManager.GetString("ToolTip_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide the currently open panel (Escape).
        /// </summary>
        public static string ToolTip_HidePanel {
            get {
                return ResourceManager.GetString("ToolTip_HidePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Isolated Storage.
        /// </summary>
        public static string ToolTip_IncreaseIS {
            get {
                return ResourceManager.GetString("ToolTip_IncreaseIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Navigation Panel (C).
        /// </summary>
        public static string ToolTip_Navigation {
            get {
                return ResourceManager.GetString("ToolTip_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the Next Heading (Down Arrow).
        /// </summary>
        public static string ToolTip_NextSection {
            get {
                return ResourceManager.GetString("ToolTip_NextSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the Next Paragraph (Right Arrow).
        /// </summary>
        public static string ToolTip_NextSentence {
            get {
                return ResourceManager.GetString("ToolTip_NextSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a local Daisy book on your computer (O).
        /// </summary>
        public static string ToolTip_OpenBook {
            get {
                return ResourceManager.GetString("ToolTip_OpenBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Book.
        /// </summary>
        public static string ToolTip_Pause {
            get {
                return ResourceManager.GetString("ToolTip_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Book.
        /// </summary>
        public static string ToolTip_Play {
            get {
                return ResourceManager.GetString("ToolTip_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the Previous Heading (Up Arrow).
        /// </summary>
        public static string ToolTip_PreviousSection {
            get {
                return ResourceManager.GetString("ToolTip_PreviousSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the Previous Paragraph (Left Arrow).
        /// </summary>
        public static string ToolTip_PreviousSentence {
            get {
                return ResourceManager.GetString("ToolTip_PreviousSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide to Adjust Volume (J to decrease, K to increase).
        /// </summary>
        public static string ToolTip_VolumeSlider {
            get {
                return ResourceManager.GetString("ToolTip_VolumeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Buttercup!.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
